---
swagger: "2.0"
info:
  description: "Created by AWS Lambda"
  version: "2022-04-04T10:27:38Z"
  title: "apis-call-function-API"
host: "a6ni5gfcg7.execute-api.eu-central-1.amazonaws.com"
basePath: "/info"
schemes:
- "https"
paths:
  /mia:
    post:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "CarInput"
        required: true
        schema:
          $ref: "#/definitions/CarInput"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/MiaOutput"
      security:
      - api_key: []
  /saboteur:
    post:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "CarInput"
        required: true
        schema:
          $ref: "#/definitions/CarInput"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/SaboteurOutput"
      security:
      - api_key: []
  /stolen:
    post:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "CarInput"
        required: true
        schema:
          $ref: "#/definitions/CarInput"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/StolenOutput"
      security:
      - api_key: []
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "x-api-key"
    in: "header"
definitions:
  StolenOutput:
    type: "object"
    properties:
      vendor:
        type: "string"
      model:
        type: "string"
      model_year:
        type: "number"
      color:
        type: "string"
      body:
        type: "string"
      kind:
        type: "string"
      purpose:
        type: "string"
      registered_at:
        type: "string"
      operation:
        type: "string"
      address:
        type: "string"
      is_registered_to_company:
        type: "boolean"
    title: "StolenOutput"
  MiaOutput:
    type: "object"
    properties:
      vendor:
        type: "string"
      model:
        type: "string"
      model_year:
        type: "number"
      color:
        type: "string"
      body:
        type: "string"
      kind:
        type: "string"
      purpose:
        type: "string"
      registered_at:
        type: "string"
      operation:
        type: "string"
      address:
        type: "string"
      is_registered_to_company:
        type: "boolean"
      is_stolen:
        type: "boolean"
    title: "MiaOutput"
  CarInput:
    type: "object"
    required:
    - "licensePlate"
    properties:
      licensePlate:
        type: "string"
      notes:
        type: "string"
      isBase64Encoded:
        type: "boolean"
    title: "CarInput"
  SaboteurOutput:
    type: "object"
    properties:
      note:
        type: "string"
      dateOfInsert:
        type: "string"
      searchName:
        type: "string"
      licensePlate:
        type: "string"
    title: "SaboteurOutput"
